name: deploy website
on:
  push:
    branches:
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - uses: cachix/install-nix-action@v27
          with:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}

        - run: nix develop --command make

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_build
